#!/usr/bin/env bash

if
  [[ -s "/usr/local/rvm/gems/ruby-2.4.0/environment" ]]
then
  source "/usr/local/rvm/gems/ruby-2.4.0/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/gems/ruby-2.4.0/environment'" >&2
  exit 1
fi
